// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXZ_z9tRHNC6m0wdsVB88aWONIUDFOv-I',
    appId: '1:1097890445055:web:be47ef5e00ebb918a4feca',
    messagingSenderId: '1097890445055',
    projectId: 'social-images-2cbed',
    authDomain: 'social-images-2cbed.firebaseapp.com',
    storageBucket: 'social-images-2cbed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD88q_e-0cxyrdWiwbcEPtIfUq3WRJfHYE',
    appId: '1:1097890445055:android:a3a0aa67c0859db4a4feca',
    messagingSenderId: '1097890445055',
    projectId: 'social-images-2cbed',
    storageBucket: 'social-images-2cbed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi0Wt_FxnadFgdFZDSIkoY20CtZZdZv8U',
    appId: '1:1097890445055:ios:e2ceb58cb3e62e9da4feca',
    messagingSenderId: '1097890445055',
    projectId: 'social-images-2cbed',
    storageBucket: 'social-images-2cbed.appspot.com',
    iosClientId:
        '1097890445055-k7vt2i5s9462g1ptlsjl11t2kcgci119.apps.googleusercontent.com',
    iosBundleId: 'com.example.Imagesio',
  );
}
